#!/usr/bin/env python3
#
#


import json
import os
import sys

base = os.getenv('HOME') + "/usr/var/sada"

try:
	bs=os.stat(base)
except:
	os.popen("mkdir -p " + base)

#if we get nothing list all buckets
try:
	bucket = sys.argv[1].replace("/","_").strip()
except:
	for dirname in os.listdir(base):
		print(dirname)
	exit()
if sys.argv[1] != bucket:
    sys.stderr.write( "Illegal character '/' in bucket name, remapping '/' to '_': " + bucket + "\n" )

#If we are not given a key, list all keys in the bucket
try:
	key = sys.argv[2].replace("/","_").strip()
except:
	#If bucket dosent exist, exit
	if not os.path.isdir( base + "/" + bucket):
		sys.stderr.write( "Unable to find bucket: " + base + "/" + bucket + "\n" )
		sys.exit(1)
	for dirname in os.listdir(base + "/" + bucket):
		print(dirname)
	exit()
	

datafile=base + "/" + bucket + "/" + key
if len(sys.argv) == 4:
	#Write mode
	value = sys.argv[3] 
	try:
		bs=os.stat(base + "/" + bucket)
	except:
		os.popen("mkdir " + base + "/" + bucket)
		sys.stderr.write( "Creating new bucket: " + bucket + "\n" )
	try:
		fh=open(datafile)
		data=json.loads(fh.read())
		fh.close()
	except:
		data={}
	try:
		if data['value'] != value:
			try:
				#Move currenty value to front of history
				data['history'].insert(0, data['value'])
				data['value'] = value
			except:
				#If we throw here we need to init history
				data['history'] = []
				data['history'].insert(0, data['value'])
				data['value'] = value
	except:
		#If we throw here we need to initalize the data
		data['value'] = value
		data['history'] = []
	fh=open(datafile, "w")
	fh.writelines(json.dumps(data, sort_keys=True, indent=4) + "\n" )
	fh.close()
	print(bucket + " " + key + " " + value)


elif len(sys.argv) == 3:
	#read mode
	try:
		fh=open(datafile)
		data=json.loads(fh.read())
		fh.close()
		print(bucket + " " + key + " " + data['value'])
	except:
		sys.stderr.write( "No such key: " + key + "\n" )
		print(bucket + " " + key + " ")
		sys.exit(1)
else:
	print("syntax error")
